import os

# MLFLOW MODEL TRACKING
MLFLOW_ENDPOINT = os.getenv("MLFLOW_ENDPOINT")
MLFLOW_EXPERIMENT = "redwine_production_test"
POSTGRES_DATABASE = os.getenv("POSTGRES_DATABASE")
POSTGRES_USERNAME = os.getenv("POSTGRES_USERNAME")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")

# METRIC FOR BEST MODEL
METRIC_BM = "r2_validation"
METRIC_BM_TYPE = "max"

# IDS
IDS_RESOURCE_ID = "Clarus_RedWine_experiment"
